package cn.com.ttblog.jfinal_bootstrap_table.model;

import cn.com.ttblog.jfinal_bootstrap_table.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
}
